swagger: "2.0"
info:
  version: 1.0.0
  title: apphub-microapp-seed
  description: A microapp example seed project for AppHub.
basePath: /api
tags:
  - name: Nav
    description: Navigation endpoints
  - name: Example
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        description: The example name

paths:

  #Nav
  /nav:
    get:
      tags:
        - Nav
      description: Get navigation array
      responses:
        200:
          description: Returns navigation array


  #Example
  /example:
    get:
      tags:
        - Example
      description: Fetch all Examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Example
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: number of items to skip
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all example

  /example/{id}:
    get:
      tags:
        - Example
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the entity to retrieve
          type: integer
      responses:
        200:
          description: Return the example with the specified id
        404:
          description: Example not

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
